price_str=input("Enter the original price[$]: ")
discount_str=input("Enter the discount percentage: ")
price=round(float(price_str),2)
discount=round(float(discount_str),2)
discount_amount=round((discount/100)*price,2)
final_price=round(price-discount_amount,2)
reduction=round(price-final_price,2)
print("The final price after a discount of",discount,"% is: $",final_price)
print("You saved: $",reduction)